name: Build App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build for ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [linux, windows]
        include:
          - platform: linux
            runs-on: ubuntu-latest
            build-script: ./build-linux.sh
          - platform: windows
            runs-on: windows-latest
            build-script: .\build-windows.ps

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install Poetry dependencies
        run: poetry install

      - name: Build portable app
        run: ${{ matrix.build-script }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-app
          path: dist/
